name: ExplorersCore
version: '2.0.1'
main: me.softsheep6.explorersCore.ExplorersCore
api-version: '1.21'
commands:
  givetotem:
    description: Gives the Totem of Infinity
    permission: explorerscore.totem
    usage: /<command>
  givecrown:
    description: Gives the Explorer's Crown
    permission: explorerscore.crown
    usage: /<command>
  givesword:
    description: Gives the Lightning Sword
    permission: explorerscore.sword
    usage: /<command>
  givehammer:
    description: Gives the Mining Hammer
    permission: explorerscore.hammer
    usage: /<command>
  givebread:
    description: Gives a loaf of Enriched Bread
    permission: explorerscore.bread
    usage: /<command>
  giveapplication:
    description: Gives a Job Application
    permission: explorerscore.job
    usage: /<command>
  giveaxe:
    description: Gives the Axe of Swiftness
    permission: explorerscore.axe
    usage: /<command>
  giverod:
    description: Gives an Inferno Rod
    permission: explorerscore.rod
    usage: /<command>
  togglemacecraftable:
    description: Toggles whether or not the mace can be crafted
    permission: explorerscore.togglemacecraftable
    usage: /<command>
  togglepvp:
    description: Toggles PVP
    permission: explorerscore.togglepvp
    usage: /<command>
  toggleend:
    description: Toggles whether or not eyes of ender can be placed on end portal frames
    permission: explorerscore.toggleend
    usage: /<command>
  togglestringduper:
    description: Toggles string dupers
    permission: explorerscore.togglestringduper
    usage: /<command>